In [11]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 50)

In [7]:
video_df = pd.read_csv("data/long_video.csv", index_col=None)
lang_df = pd.read_csv("data/wide_lang.csv", index_col=None)

In [8]:
video_df.shape, lang_df.shape

((27288, 13), (939, 29))

In [9]:
video_df.head(6)

,key,year,program,lang,genre,channel,ats,rating,reach,gender,age,skintone,faces
0,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,young,light,3
1,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,young,medium,0
2,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,young,dark,1
3,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,adult,light,2211
4,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,adult,medium,1390
5,Ben_26,2018,adorini,BENGALI,DRAMA/SOAP,STAR Jalsha,49.665179,2.48,5.0,male,adult,dark,44

In [12]:
lang_df.head(6)

,key,year,program,lang,genre,channel,ats,rating,reach,male_faces,female_faces,young_faces,adult_faces,middle_aged_faces,old_faces,light_faces,medium_faces,dark_faces,faces,derogatory,controversial,male_name,female_name,unisex_name,hindu_name,muslim_name,christian_name,transcript,non_stopword_transcript
0,8V-mhzGr8rA,2018,ranu pelo lottery,BENGALI,DRAMA/SOAP,Zee Bangla,61.687951,4.45,7.22,9691,7470,195,13900,2655,411,13685,3314,162,17161,7,0,9,8,1,0,4,5,1662,919
1,sR0g8hDld8I,2018,ranu pelo lottery,BENGALI,DRAMA/SOAP,Zee Bangla,61.687951,4.45,7.22,5318,7742,514,10345,1590,611,9403,3072,585,13060,1,0,10,10,0,0,5,5,1316,728
2,oXdB7Otc6Lo,2018,ranu pelo lottery,BENGALI,DRAMA/SOAP,Zee Bangla,61.687951,4.45,7.22,8462,10474,643,10334,7027,932,15592,3231,113,18936,7,0,14,13,0,1,8,6,1990,1167
3,RMmSjFxOPKY,2018,ranu pelo lottery,BENGALI,DRAMA/SOAP,Zee Bangla,61.687951,4.45,7.22,7790,11825,280,12029,6146,1160,15402,4130,83,19615,7,0,15,14,0,1,8,7,1925,1096
4,zZ46moWsngI,2018,ranu pelo lottery,BENGALI,DRAMA/SOAP,Zee Bangla,61.687951,4.45,7.22,8627,12797,1021,13297,5884,1222,15377,5429,618,21424,2,0,19,19,0,0,13,6,1779,978
5,idb2-OGdIMc,2018,joy baba lokenath,BENGALI,DRAMA/SOAP,Zee Bangla,48.152296,3.93,8.17,10835,11690,7478,11828,3219,0,18831,2723,971,22525,0,0,11,11,0,0,7,4,1806,885

In [16]:
print((video_df.groupby("key").apply(len) != 24).sum())
print(video_df["key"].unique().size)

0
1137

In [20]:
print((lang_df["derogatory"] > lang_df["transcript"]).sum())
print((lang_df["derogatory"] > lang_df["non_stopword_transcript"]).sum())

0
0